export const food_timing_category = ["break-fast", "Lunch", "Dinner"];

export const food_category = ["all", "veg", "non_veg"];

export const get_food_details = [
  {
    food_id: 1,
    food_name: "Butter Chicken",
    food_category: "veg",
    reviews: 14404,
    star: 2,
    description: "Spicy chicken sandwich with fries",
    timing: "break-fast",
    price: 170,
  },
  {
    food_id: 2,
    food_name: "Palak Paneer",
    food_category: "veg",
    reviews: 7544,
    star: 2,
    description: "Vegetarian pizza with extra cheese",
    timing: "Lunch",
    price: 130,
  },
  {
    food_id: 3,
    food_name: "Chana Masala",
    food_category: "non_veg",
    reviews: 7526,
    star: 3,
    description: "Grilled salmon with asparagus",
    timing: "Dinner",
    price: 50,
  },
  {
    food_id: 4,
    food_name: "Aloo Gobi",
    food_category: "veg",
    reviews: 6592,
    star: 4,
    description: "Beef stir fry with rice",
    timing: "break-fast",
    price: 190,
  },
  {
    food_id: 5,
    food_name: "Baingan Bharta",
    food_category: "veg",
    reviews: 15742,
    star: 1,
    description: "Caesar salad with grilled chicken",
    timing: "Lunch",
    price: 110,
  },
  {
    food_id: 6,
    food_name: "Samosa",
    food_category: "veg",
    reviews: 7289,
    star: 1,
    description: "Pesto pasta with garlic bread",
    timing: "Dinner",
    price: 140,
  },
  {
    food_id: 7,
    food_name: "Tandoori Chicken",
    food_category: "veg",
    reviews: 18474,
    star: 4,
    description: "Taco salad with avocado dressing",
    timing: "break-fast",
    price: 160,
  },
  {
    food_id: 8,
    food_name: "Chicken Tikka Masala",
    food_category: "veg",
    reviews: 24762,
    star: 0,
    description: "Mushroom risotto with truffle oil",
    timing: "Lunch",
    price: 90,
  },
  {
    food_id: 9,
    food_name: "Biryani",
    food_category: "veg",
    reviews: 23307,
    star: 5,
    description: "Fish and chips with tartar sauce",
    timing: "Dinner",
    price: 200,
  },
  {
    food_id: 10,
    food_name: "Rogan Josh",
    food_category: "non_veg",
    reviews: 22887,
    star: 3,
    description: "Chicken alfredo with broccoli",
    timing: "break-fast",
    price: 125,
  },
  {
    food_id: 11,
    food_name: "Dal Makhani",
    food_category: "non_veg",
    reviews: 14695,
    star: 3,
    description: "Veggie burger with sweet potato fries",
    timing: "Lunch",
    price: 150,
  },
  {
    food_id: 12,
    food_name: "Matar Paneer",
    food_category: "non_veg",
    reviews: 11377,
    star: 1,
    description: "Shrimp scampi with linguine",
    timing: "Dinner",
    price: 95,
  },
  {
    food_id: 13,
    food_name: "Malai Kofta",
    food_category: "non_veg",
    reviews: 24078,
    star: 1,
    description: "Beef fajitas with guacamole",
    timing: "break-fast",
    price: 120,
  },
  {
    food_id: 14,
    food_name: "Fish Curry",
    food_category: "veg",
    reviews: 10263,
    star: 0,
    description: "Tomato soup with grilled cheese sandwich",
    timing: "Lunch",
    price: 110,
  },
  {
    food_id: 15,
    food_name: "Keema",
    food_category: "non_veg",
    reviews: 22506,
    star: 2,
    description: "Pad Thai with shrimp",
    timing: "Dinner",
    price: 160,
  },
  {
    food_id: 16,
    food_name: "Vindaloo",
    food_category: "non_veg",
    reviews: 12614,
    star: 0,
    description: "Lamb chops with roasted potatoes",
    timing: "break-fast",
    price: 120,
  },
  {
    food_id: 17,
    food_name: "Pakora",
    food_category: "veg",
    reviews: 1479,
    star: 3,
    description: "Spinach and feta omelette with toast",
    timing: "Lunch",
    price: 30,
  },
  {
    food_id: 18,
    food_name: "Papdi Chaat",
    food_category: "veg",
    reviews: 1126,
    star: 5,
    description: "Beef and broccoli with white rice",
    timing: "Dinner",
    price: 80,
  },
  {
    food_id: 19,
    food_name: "Dosa",
    food_category: "veg",
    reviews: 19636,
    star: 5,
    description: "Chicken tikka masala with naan bread",
    timing: "break-fast",
    price: 50,
  },
  {
    food_id: 20,
    food_name: "Idli",
    food_category: "non_veg",
    reviews: 22564,
    star: 1,
    description: "Pulled pork sandwich with coleslaw",
    timing: "Lunch",
    price: 60,
  },
  {
    food_id: 21,
    food_name: "Sambhar",
    food_category: "veg",
    reviews: 18299,
    star: 2,
    description: "Grilled portobello mushroom burger with fries",
    timing: "Dinner",
    price: 70,
  },
  {
    food_id: 22,
    food_name: "Rasam",
    food_category: "non_veg",
    reviews: 15952,
    star: 5,
    description: "Beef bourguignon with mashed potatoes",
    timing: "break-fast",
    price: 140,
  },
  {
    food_id: 23,
    food_name: "Upma",
    food_category: "veg",
    reviews: 10402,
    star: 4,
    description: "Chicken shawarma with hummus",
    timing: "Lunch",
    price: 40,
  },
  {
    food_id: 24,
    food_name: "Pongal",
    food_category: "non_veg",
    reviews: 10281,
    star: 0,
    description: "Baked ziti with garlic bread",
    timing: "Dinner",
    price: 70,
  },
  {
    food_id: 25,
    food_name: "Bisi Bele Bath",
    food_category: "veg",
    reviews: 22340,
    star: 3,
    description: "Vegetable stir fry with noodles",
    timing: "break-fast",
    price: 60,
  },
  {
    food_id: 26,
    food_name: "Mysore Pak",
    food_category: "non_veg",
    reviews: 6137,
    star: 1,
    description: "Beef and mushroom stroganoff with egg noodles",
    timing: "Lunch",
    price: 20,
  },
  {
    food_id: 27,
    food_name: "Gulab Jamun",
    food_category: "non_veg",
    reviews: 24947,
    star: 4,
    description: "Chicken Caesar wrap with chips",
    timing: "Dinner",
    price: 40,
  },
  {
    food_id: 28,
    food_name: "Rasmalai",
    food_category: "non_veg",
    reviews: 22680,
    star: 5,
    description: "Lobster bisque with garlic bread",
    timing: "break-fast",
    price: 50,
  },
  {
    food_id: 29,
    food_name: "Jalebi",
    food_category: "veg",
    reviews: 10021,
    star: 2,
    description: "Vegan chili with cornbread",
    timing: "Lunch",
    price: 30,
  },
  {
    food_id: 30,
    food_name: "Kulfi",
    food_category: "non_veg",
    reviews: 7870,
    star: 3,
    description: "Beef and vegetable soup with crusty bread",
    timing: "Dinner",
    price: 65,
  },
];
